# The URL the site will be built for
base_url = "https://sanchitgupta.vercel.app/"

# The site title and description; used in feeds by default.
title = "Sanchit Gupta"
description = "Hey, I'm Sanchit Gupta from India. I love programming, gameing and learning new things!"

# The default language; used in feeds.
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true


# The taxonomies to be rendered for the site and their configuration of the default languages
taxonomies = [
  {name = "tags", feed = true, paginate_by = 10},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# When set to "true", emoji aliases translated to their corresponding
# Unicode emoji equivalent in the rendered Markdown files. (e.g.: :smile: => 😄)
render_emoji = true

# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = true

# Whether to set rel="nofollow" for all external links
external_links_no_follow = true

# Whether to set rel="noreferrer" for all external links
external_links_no_referrer = true

# Whether smart punctuation is enabled (changing quotes, dashes, dots in their typographic form)
# For example, `...` into `…`, `"quote"` into `“curly”` etc
smart_punctuation = true

[extra]
long_title = "Sanchit Gupta"
favicon = "/assets/images/profile.jpg"
logo = "/assets/images/logo.png"

[[extra.footer.socials]]
name = "mail"
label = "Email"
value = "sanchitgupta0101@gmail.com"
link = "mailto:sanchitgupta0101@gmail.com"
[[extra.footer.socials]]
name = "instagram"
label = "Instagram"
value = "@sanchitgupta0101"
link = "https://www.instagram.com/sanchitgupta0101/"
[[extra.footer.socials]]
name = "discord"
label = "Discord"
value = "g.froster"
link = "https://discord.com/users/451054079813091328"
[[extra.footer.socials]]
name = "linkedin"
label = "Likedin"
value = "in/aboutsanchitgupta"
link = "https://www.linkedin.com/in/aboutsanchit/"
[[extra.footer.socials]]
name = "github"
label = "Github"
value = "gsanchit01"
link = "https://github.com/gsanchit01"

[[extra.links]]
name = "Home"
path = "/"
[[extra.links]]
name = "About"
path = "/about"
[[extra.links]]
name = "Source"
path = "https://github.com/gsanchit01/sanchitgupta"
