[build]
publish = "public"
command = "cd netlify/functions && npm install && cd ../.. && zola build"

[build.environment]
ZOLA_VERSION = "0.17.2"

[functions]
directory = "netlify/functions"

[dev]
command = "/tmp/zola serve"
targetPort = 1111
port = 8888

[context.deploy-preview]
command = "zola build --base-url $DEPLOY_PRIME_URL"

[[headers]]
for = "/.well-known/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"
